var productCategoryList = [
  "Laptop",
  "Monitor",
  "Desktop & Mini PC",
  "PC & Laptop gaming",
  "Computer Components",
  "Computer & Laptop Accessories",
  "Smartphone",
  "Tablet",
  "Smartphone & Tablet Accessories",
  "Smartphone & Tablet Components",
  "Cable & Adaptor",
  "Wearable Devices",
  "Game Console",
  "Game Console Accessories",
  "Media Penyimpanan Data",
  "Networking",
  "Others",
];